name: _job_build

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      cflags:
        required: false
        type: string
        default: ''
      rustflags:
        required: false
        type: string
        default: ''
      configure:
        required: false
        type: string
        default: ''
      runner:
        required: false
        type: string
        default: 'ubuntu-24.04'
      continue:
        required: true
        type: boolean

  workflow_dispatch:
    inputs:
      name:
        description: 'Build name'
        required: true
        type: string
        default: 'custom-proton'
      cflags:
        description: 'CFLAGS'
        required: false
        type: string
        default: ''
      rustflags:
        description: 'RUSTFLAGS'
        required: false
        type: string
        default: ''
      configure:
        description: 'Configure options'
        required: false
        type: string
        default: ''
      runner:
        description: 'Runner OS'
        required: false
        type: string
        default: 'ubuntu-24.04'
      continue:
        description: 'Continue on error'
        required: false
        type: boolean
        default: false

jobs:
  proton:
    name: Build ${{ inputs.name }}
    runs-on: ${{ inputs.runner }}
    continue-on-error: ${{ inputs.continue }}
    steps:

    #- name: Debloat GitHub runner - Addtional disk space not needed, not doing this speeds up deployment 
      #uses: endersonmenezes/free-disk-space@v3
      #with:
        #remove_android: true
        #remove_dotnet: true
        #remove_haskell: true
        #remove_tool_cache: true
        #remove_swap: true
        #remove_packages: >-
          #azure-cli
          #google-cloud-cli
          #microsoft-edge-stable
          #google-chrome-stable
          #firefox
          #postgresql*
          #temurin-*
          #*llvm*
          #mysql*
          #dotnet-sdk-*
        #remove_packages_one_command: false
        #remove_folders: >-
          #/usr/share/swift
          #/usr/share/miniconda
          #/usr/share/az*
          #/usr/local/lib/node_modules
          #/usr/local/share/chromium
          #/usr/local/share/powershell
          #/usr/local/julia
          #/usr/local/aws-cli
          #/usr/local/aws-sam-cli
          #/usr/share/gradle
        #testing: false

    - name: Prepare host
      run: sudo apt update && sudo apt-get install -y ccache fontforge-nox ninja-build meson g++-mingw-w64 glslang-tools 

    - name: Checkout
      uses: actions/checkout@v6
      with:
        fetch-depth: 0
        fetch-tags: true
        submodules: false


    - name: Clone Proton-GE and patch # (CatchyOS Proton has not had an update in a while. So use which ever is the latest or best. Patching saves build time and requires less maintance. ) 
      run: | 
        curl -L "$(curl -s https://api.github.com/repos/GloriousEggroll/proton-ge-custom/releases/latest | grep 'browser_download_url.*x86_64.tar.gz' | cut -d '"' -f 4)" -o GE-Proton-latest.tar.gz
        mkdir -p ~/GE-Proton-latest

        tar -xf GE-Proton-latest.tar.gz \
          --strip-components=1 \
          -C ~/GE-Proton-latest/

        ls ~/GE-Proton-latest/
        ls ~/GE-Proton-latest/files
        ls ~/GE-Proton-latest/files/lib
        ls ~/GE-Proton-latest/files/lib/wine
        ls ~/GE-Proton-latest/files/lib/wine/dxvk
        ls ~/GE-Proton-latest/files/lib/wine/dxvk/x86_64-windows

        - name: Build DXVK-Async
              run: | 
                git clone --branch v3.0 --recursive https://github.com/doitsujin/dxvk.git
                cd dxvk
                curl -LO "https://gitlab.com/Ph42oN/dxvk-gplasync/-/raw/main/patches/dxvk-gplasync-master.patch?ref_type=heads"
                curl -LO "https://gitlab.com/Ph42oN/dxvk-gplasync/-/raw/main/patches/global-dxvk.conf.patch?ref_type=heads"
                patch -p1 < dxvk-gplasync-master.patch
                patch -p1 < global-dxvk.conf.patch
        
                # Build DXVK to a temporary output directory
                ./package-release.sh master build_output --no-package
        
                # Create destination directories for GE-Proton
                mkdir -p ~/GE-Proton-latest/files/lib/wine/dxvk/x86_64-windows
                mkdir -p ~/GE-Proton-latest/files/lib/wine/dxvk/i686-windows
        
                # Copy x64 and x32 build outputs into respective Proton folders
                cp -r build_output/dxvk-master/x64/*.dll ~/GE-Proton-latest/files/lib/wine/dxvk/x86_64-windows/
                cp -r build_output/dxvk-master/x32/*.dll ~/GE-Proton-latest/files/lib/wine/dxvk/i686-windows/
        
                # Verify 64-bit files exist
                ls -la ~/GE-Proton-latest/files/lib/wine/dxvk/x86_64-windows/
                cd ..

    - name: Patch DXVK to use DXVK-gplasync
      run: | # Delete Old version of DXVK
        cd ~/GE-Proton-latest/files/lib/wine/dxvk/x86_64-windows
        cp ~/dxvk/*.dll ~/GE-Proton-latest/files/lib/wine/dxvk/x86_64-windows

    - name: Upload artifact ${{ inputs.name }}.tar.xz
      uses: actions/upload-artifact@v6
      with:
        name: ${{ inputs.name }}.tar.xz
        path: ./build/${{ inputs.name }}.tar.xz

    - name: Upload artifact ${{ inputs.name }}.sha512sum
      uses: actions/upload-artifact@v6
      with:
        name: ${{ inputs.name }}.sha512sum
        path: ./build/${{ inputs.name }}.sha512sum
