name: Release

on:
  release:
    types: [ published ]

jobs:
  build:
    strategy:
      matrix:
        include:
          - name: proton-${{ github.ref_name }}-x86_64
            cpu_arch: nocona
            cpu_tune: core-avx2
          - name: proton-${{ github.ref_name }}-x86_64_v3
            cpu_arch: core-avx2
            cpu_tune: core-avx2
    name: Build
    uses: ./.github/workflows/build.yml
    with:
      name: ${{ matrix.name }}
      cpu_arch: ${{ matrix.cpu_arch }}
      cpu_tune: ${{ matrix.cpu_tune }}

  upload:
    strategy:
      matrix:
        include:
          - name: proton-${{ github.ref_name }}-x86_64
          - name: proton-${{ github.ref_name }}-x86_64_v3
    name: Upload
    needs: build
    uses: ./.github/workflows/upload.yml
    with:
      name: ${{ matrix.name }}
