name: Upload

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string

jobs:
  upload:
    name: Upload ${{ inputs.name }}
    strategy:
      matrix:
        include:
          - file: ${{ inputs.name }}.tar.xz
          - file: ${{ inputs.name }}.sha512sum
    runs-on: ubuntu-latest
    steps:
      - name: Download ${{ matrix.file }} artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.file }}

      - name: Upload ${{ matrix.file }} to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
          file: ${{ matrix.file }}
          overwrite: false
